### ISSUE TITLE
[Fix] Website rewrite

### ISSUE THREAD

**Issue by Stylix58** [fosscord/fosscord-landingpage#1]
I should think I can start the making of a website for Fosscord.

**Frontend:**
HTML (Pug), CSS, JS

**Backend:**
NodeJS:
- Express

**Comment by Stylix58** [comment]
I will change the package manager to pnpm.

**Comment by Flam3rboy** [comment]
What’s pnpm? I only know npm xD

**Comment by Stylix58** [comment]
https://pnpm.io/

**Comment by Stylix58** [comment]
Yes.
