### ISSUE TITLE
Needed Improvements

### ISSUE THREAD

**Issue by xNaCly** [fosscord/fosscord-landingpage#14]
- General:
  - this looks disgusting, either remove the border and replace the background with a greyish color or fill it with the same color the border is in
  ![image](https://user-images.githubusercontent.com/47723417/121430850-ed559700-c978-11eb-9d10-e40413258096.png)

- Design inconsistencies:
  - either put all elements in the center or push the ul to the end of the navbar (accounting for margin on both sides)
  ![image](https://user-images.githubusercontent.com/47723417/121429999-d6627500-c977-11eb-88a6-fd953fbd47c8.png)

  - make `Fosscord is` a header
  ![image](https://user-images.githubusercontent.com/47723417/121430304-32c59480-c978-11eb-9a09-479c016aa750.png)  

  - colors do not match (picture and page)
  ![image](https://user-images.githubusercontent.com/47723417/121430431-5ee11580-c978-11eb-9202-0b73723b351f.png)

  - remove padding/margin around the `ul`
  ![image](https://user-images.githubusercontent.com/47723417/121430478-71f3e580-c978-11eb-8c21-130778db72e1.png)
  
  - navbar background on scroll does not match our ui frameworks design dogma (too dark)
  ![image](https://user-images.githubusercontent.com/47723417/121430681-aebfdc80-c978-11eb-84c9-71eeb77a383e.png)

- Boring design choices:
  - nothing in the background, looks boring
  ![image](https://user-images.githubusercontent.com/47723417/121430168-0f9ae500-c978-11eb-8d07-5ce17728cb6d.png)

  - not the right place for that, replace it with a footer containing links
  ![image](https://user-images.githubusercontent.com/47723417/121430794-d31bb900-c978-11eb-8a24-4e58756e4345.png)

**Comment by Stylix58** [comment]
I will try fix it now

**Comment by Stylix58** [comment]
For the footer, i can't do nothing for now (I need help for this).

**Comment by Stylix58** [comment]
#15

**Comment by xNaCly** [comment]
> For the footer, i can't do nothing for now (I need help for this).

I am looking into it later today.

**Comment by xNaCly** [comment]
now irrelevant because of https://github.com/fosscord/fosscord-landingpage/pull/21
