### ISSUE TITLE
Suggestion to add "Still under development" or something similiar to the header on the landing page 

### ISSUE THREAD

**Issue by nasseef20** [fosscord/fosscord-landingpage#19]
I learnt about fosscord from a reddit post which gave a link to this website (which said nothing about this being a work in progress  by the way). I clicked "Open web client" and attempted to log in. I even tried creating an account. None of that worked. 

Only after visiting the Github repo page I understood that this is still a work in progress. There is no indication on the landing page about this being a work in progress. This feels a bit confusing or misleading.

How about adding a "Still under development" or "Work in progress" or something similar to the header of this website? You can also add a hyperlink to Fosscord's Twitter handle saying "Get notified when it releases" or something similiar.

**Comment by Flam3rboy** [comment]
Yes good idea 😄👍

**Comment by Stylix58** [comment]
Ok, i will add it! (easy because its use bootstrap)

**Comment by xNaCly** [comment]
done in https://github.com/fosscord/fosscord-landingpage/commit/bc56a6d3dc8d4c21da777466dac3cd82e575483a
