### ISSUE TITLE
Not mobile responsive

### ISSUE THREAD

**Issue by Stylix58** [fosscord/fosscord-landingpage#22]
The waves are buggy!

![IMG_20210723_152427](https://user-images.githubusercontent.com/63605602/126788260-798a8907-a6f5-486a-9803-4f57377c38ce.jpg)

**Comment by Flam3rboy** [comment]
I'll remove them on mobile

**Comment by Flam3rboy** [comment]
![image](https://user-images.githubusercontent.com/34555296/126788399-3282743d-7bae-457b-8cf2-9f8f2a45242e.png)
works for me tho, so the browser engine doesn't render z-index correctly

**Comment by Stylix58** [comment]
Bruh but ok.

**Comment by Flam3rboy** [comment]
fixed in 61e18b6

**Comment by Stylix58** [comment]
If you will commit, I close this.
