### ISSUE TITLE
Use BootstrapVue

### ISSUE THREAD

**Issue by Stylix58** [fosscord/fosscord-landingpage#23]
For now, this app use a custom Bootstrap CSS file. But, we can use [BootstrapVue](https://bootstrap-vue.org).

**Comment by Intevel** [comment]
No, we dont want use Bootstrap Vue. 
it is unnecessary and complicated. And even another version I think

**Comment by Stylix58** [comment]
Ok but if you want, I can do the migration to this framework.

**Comment by Intevel** [comment]
No sorry

**Comment by keanuplayz** [comment]
> we don't want to
> still offers to do it
What's so difficult to understand about "no"?

**Comment by xNaCly** [comment]
> > we don't want to
> > still offers to do it
> 
> What's so difficult to understand about "no"?

everytime
