### ISSUE TITLE
The instances section don't appear on mobile navbar

### ISSUE THREAD

**Issue by Stilic** [fosscord/fosscord-landingpage#32]
The title describe my problem. Here is a capture also:
![IMG_20210906_071642](https://user-images.githubusercontent.com/63605602/132164196-59b825c5-fafb-4b7f-be19-dcbedb789fcf.jpg)

**Comment by xNaCly** [comment]
fixed in: https://github.com/fosscord/fosscord-landingpage/commit/bf5169952c8ee4f10ad1c9fedda05c7b6fcc9f69
