### ISSUE TITLE
Rewrite using React

### ISSUE THREAD

**Issue by Stilic** [fosscord/fosscord-landingpage#37]
Because in every repo we use React, we should rewrite the website to a React-based framework, like Next.js or Gatsby.

**Comment by Flam3rboy** [comment]
We'll not do it, as it is a waste of time. However the community can feel free to rewrite it using React.

**Comment by Stilic** [comment]
I can do it, when I will get time.

**Comment by developomp** [comment]
I tried rewriting in react last month. You might wanna find a good alternative to [NuxtJS pages](https://nuxtjs.org/docs/directory-structure/pages). I don't like the idea of replacing something that automatically handles the route for you with something that doesn't.

**Comment by khalby786** [comment]
@Stilic you really hate NuxtJS and Vue, don't you?

**Comment by Stilic** [comment]
Not really. I just prefer do it in React like we doing already for the client.

**Comment by developomp** [comment]
React also has more developers than vue and other repos are already using react anyway.

**Comment by khalby786** [comment]
> Not really. I just prefer do it in React like we doing already for the client.

Fair point, but like @Flam3rboy said, rewriting it would be a waste of time.

**Comment by developomp** [comment]
@Flam3rboy would you accept the pr if someone does rewrite in react?

**Comment by khalby786** [comment]
Last I heard, they were planning to rewrite it in NuxtJS (Vue) itself but with proper use of it and additionally, Tailwind support.
